import { build } from "electron-builder";

import dotenv from "dotenv";
dotenv.config();

build({
  config: {
    productName: "Elephicon",
    artifactName: "${productName}-${version}-${platform}-${arch}.${ext}",
    copyright: "© 2020 sprout2000 and other contributors.",
    directories: {
      output: "release",
      buildResources: "assets",
    },
    files: [
      "dist/**/*",
      "!node_modules/@electron/notarize",
      "!node_modules/@types/mime-types",
      "!node_modules/@types/node",
      "!node_modules/@types/react",
      "!node_modules/@types/react-dom",
      "!node_modules/@typescript-eslint/eslint-plugin",
      "!node_modules/@typescript-eslint/parser",
      "!node_modules/copy-webpack-plugin",
      "!node_modules/cross-env",
      "!node_modules/css-loader",
      "!node_modules/dotenv",
      "!node_modules/electron-builder",
      "!node_modules/electronmon",
      "!node_modules/eslint",
      "!node_modules/eslint-config-prettier",
      "!node_modules/eslint-plugin-react",
      "!node_modules/eslint-plugin-react-hooks",
      "!node_modules/html-webpack-plugin",
      "!node_modules/mini-css-extract-plugin",
      "!node_modules/npm-run-all",
      "!node_modules/prettier",
      "!node_modules/rimraf",
      "!node_modules/sass",
      "!node_modules/sass-loader",
      "!node_modules/ts-loader",
      "!node_modules/ts-node",
      "!node_modules/typescript",
      "!node_modules/wait-on",
      "!node_modules/webpack",
      "!node_modules/webpack-cli",
    ],
    win: {
      icon: "assets/icon.ico",
      target: ["appx"],
      publisherName: "sprout2000",
      asarUnpack: "dist/images/icon.png",
    },
    appx: {
      backgroundColor: "#1d3557",
      displayName: "Elephicon",
      showNameOnTiles: true,
      languages: ["en-US", "ja-JP"],
      publisherDisplayName: "sprout2000",
      applicationId: "sprout2000.Elephicon",
      publisher: process.env.PUBLISHER,
      identityName: process.env.IDENTITY_NAME,
    },
  },
});
